version: '3.9'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    volumes:
      #- dev-dbdata01:/data/db
      #- dev-dbconfig01:/data/configdb
      - ./DBM/mongodb-dev/init:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    restart: unless-stopped
    environment:
      MONGODB_INITDB_ROOT_USERNAME: testuser
      MONGODB_INITDB_ROOT_PASSWORD: testpass
      MONGODB_INITDB_DATABASE: jotajotijp-dev
      TZ: "Asia/Tokyo"

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: testuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: testpass
      TZ: "Asia/Tokyo"
      ME_CONFIG_MONGODB_URL: mongodb://testuser:testpass@jotajotijp-dev:27017/ 
    depends_on:
      - mongodb

#volumes:
  #dev-dbdata01:
  #dev-dbconfig01:


